package commons;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Column;
import javax.persistence.GenerationType;
import java.util.Objects;

/**
 * The type Leaderboard entry.
 */
@Entity(name = "LeaderboardEntry")
public class LeaderboardEntry {

    //auto generate the id for the user with a sequence generator
    @Id
    @SequenceGenerator(
            name = "entry_seq",
            sequenceName = "entry_seq",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "entry_seq"
    )
    @Column(
            name = "id",
            updatable = false
    )
    public Long id;

    @Column(
            name = "name",
            nullable = false,
            columnDefinition = "TEXT"
    )
    private String name;

    @Column(
            name = "score",
            nullable = false
    )
    private int score;

    /**
     * Instantiates a new Leaderboard entry; id is autogenerated so we don't take it as parameter
     *
     * @param name  the name
     * @param score the score
     */
    public LeaderboardEntry(String name, int score) {
        this.name = name;
        this.score = score;
    }

    public LeaderboardEntry(long id, String name, int score) {
        this.id = id;
        this.name = name;
        this.score = score;
    }

    /**
     * empty, package level constructor for object mappers
     */
    LeaderboardEntry(){

    }

    /**
     * Gets the id.
     *
     * @return the id
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Gets the score.
     *
     * @return the score
     */
    public int getScore() {
        return score;
    }

    /**
     * Sets name.
     *
     * @param name the name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Sets score.
     *
     * @param score the score
     */
    public void setScore(int score) {
        this.score = score;
    }

    /**
     * Generic toString method
     *
     * @return a string representation of the leaderboard entry
     */
    @Override
    public String toString() {
        return "LeaderboardEntry{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", score=" + score +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof LeaderboardEntry)) return false;
        LeaderboardEntry that = (LeaderboardEntry) o;
        return score == that.score && Objects.equals(id, that.id) && Objects.equals(name, that.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, score);
    }
}
